version: '3'
services:
  bs_administration:
    build: ./businessservices/bs_administration  # build the image from the Dockerfile
    ports:
      - "9100:9100"
  bs_movements:
    build: ./businessservices/bs_movements
    ports:
      - "9110:9110"
  ds_administration:
    build: ./dataservices/ds_administration
    ports:
      - "9000:9000"
    depends_on:
      - mongodb
  ds_movements:
    build: ./dataservices/ds_movements
    ports:
      - "9010:9010"
    #links:
    #  - mongo
  mongodb:
    container_name: mongo
    restart: always
    image: mongo:3 # from docker hub
    environment:
      # provide your credentials here
      - AUTH=yes
      - MONGO_INITDB_ROOT_USERNAME=mesteban
      - MONGO_INITDB_ROOT_PASSWORD=newuser1
      # - MONGODB_ADMIN_USER=mesteban
      # - MONGODB_ADMIN_PASS=newuser1
      - MONGODB_APPLICATION_DATABASE=myexpenses
    ports:  # local machine: container
      - "27107:27107"
    # no --auth is needed here as presence of username and password add this option automatically
    command: mongod
    